# Generated by Django 4.0.6 on 2022-07-25 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='newField',
            field=models.TextField(default='test'),
        ),
    ]
